################################################################################
# HOMELAB
################################################################################

include:
    #############################################################################
    # CORE
    #############################################################################
    - apps/core/caddy.yaml # Caddy (Reverse Proxy)
    - apps/core/authelia.yaml # Authelia (Authentication & Identity)
    - apps/core/socket-proxy.yaml # Socket Proxy (Secure access to Docker API)
    - apps/core/cloudflared.yaml # Cloudflared (Remote access via Cloudflare)
    - apps/core/whoami.yaml # WhoAmI (Test WebServer)
    - apps/core/coredns.yaml # CoreDNS (DNS Server)

    #############################################################################
    # MEDIA
    #############################################################################
    - apps/media/gluetun.yaml # Gluetun (VPN Client)
    - apps/media/jellyfin.yaml # Jellyfin (Media Server)
    - apps/media/qbittorrent.yaml # qBittorrent (Torrent Client)
    - apps/media/flaresolverr.yaml # FlareSolverr (DDoS-GUARD Bypasser)
    - apps/media/prowlarr.yaml # Prowlarr (Indexer)
    - apps/media/radarr.yaml # Radarr (Movie Downloads)
    - apps/media/sonarr.yaml # Sonarr (TV Show Downloads)
    - apps/media/bazarr.yaml # Subtitle (Subtitle Downloads)
    - apps/media/recyclarr.yaml # Recyclarr (Automatically synchronize TRaSH Guides)
    - apps/media/tofu.yaml # OpenTofu (Arr Configuration Management)

    #############################################################################
    # MISCELLANEOUS
    #############################################################################

    # - apps/chat-gpt-next-web.yaml # ChatGPT Next Web
    # - apps/chatgpt-in-slack.yaml # ChatGPT Slack Bot
    # - apps/libreoffice.yaml # LibreOffice (Office Suite)
    # - apps/umami.yaml # Umami Analytics
    # - apps/homeassistant/docker-compose.yaml # Home Assistant (Smart Home)
    # - apps/healthchecks.yaml # Healthchecks (Monitoring)

################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
    proxy: # reverse-proxy network
        driver: bridge
    docker: # docker-socket network
        driver: bridge