services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - ${CONFIGS_DIR}/prowlarr:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PROWLARR__AUTH__APIKEY: ${PROWLARR_APIKEY}
      PROWLARR__AUTH__METHOD: External
    healthcheck:
      test: ["CMD", "curl", "-f", http://localhost:9696/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    # Run through VPN
    network_mode: service:gluetun
    depends_on:
      - gluetun
