services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    volumes:
      - ${CONFIGS_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      RADARR__AUTH__APIKEY: ${RADARR_APIKEY}
      RADARR__AUTH__METHOD: External
    healthcheck:
      test: ["CMD", "curl", "-f", http://localhost:7878/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    # Run through VPN
    network_mode: service:gluetun
    depends_on:
      - gluetun
