services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - ${CONFIGS_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${SHOWS_DIR}:/shows
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SONARR__AUTH__APIKEY: ${SONARR_APIKEY}
      SONARR__AUTH__METHOD: External
    healthcheck:
      test: ["CMD", "curl", "-f", http://localhost:8989/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    # Run through VPN
    network_mode: service:gluetun
    depends_on:
      - gluetun