configs:
  authelia_config:
    content: | # yaml
      server:
        address: 'tcp://0.0.0.0:9091/'

      log:
        level: debug

      theme: auto

      totp:
        issuer: ${DOMAIN_NAME}

      identity_validation:
        reset_password:
          # CHANGE THIS - Generate with: openssl rand -hex 32
          jwt_secret: a_very_important_secret

      authentication_backend:
        file:
          path: '/config/users_database.yml'

      access_control:
        default_policy: deny
        rules:
          - domain: ${WHOAMI_SUBDOMAIN:-whoami}.${DOMAIN_NAME}
            policy: two_factor

      session:
        # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
        secret: 'insecure_session_secret'
        cookies:
          - name: 'authelia_session'
            domain: ${DOMAIN_NAME}
            authelia_url: 'https://${AUTHELIA_SUBDOMAIN:-authelia}.${DOMAIN_NAME}/'
            # default_redirection_url: 'https://${AUTHELIA_SUBDOMAIN:-authelia}.${DOMAIN_NAME}/'
            expiration: '1 hour'
            inactivity: '5 minutes'

      regulation:
        max_retries: 3
        find_time: '2 minutes'
        ban_time: '5 minutes'

      storage:
        encryption_key: 'you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this'
        local:
          path: /config/db.sqlite3

      notifier:
        # For testing - use SMTP in production
        filesystem:
          filename: /config/notification.txt

  users_database:
    content: | # yaml
      users:
        Aaron@AutomateAaron.com:
          disabled: false
          displayname: 'Aaron Brock ☂️'
          # Password is authelia
          password: '$$argon2id$$v=19$$m=65536,t=3,p=4$$82a1q/sTLzicz/ynyN0p1w$$7DbBZYuKOpUnRohndRbvblVU7dagDvI/a6pRDSqCyPc'  # yamllint disable-line rule:line-length
          email: 'aaron@automateaaron.com'
          groups:
            - 'admins'
            - 'dev'

services:
  authelia:
    container_name: 'authelia'
    image: 'authelia/authelia'
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - caddy
    configs:
      - source: authelia_config
        target: /config/configuration.yml
      - source: users_database
        target: /config/users_database.yml

    volumes:
      - '${CONFIGS_DIR}/authelia:/config'

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - 9091:9091
    labels:
      caddy: ${AUTHELIA_SUBDOMAIN:-authelia}.${DOMAIN_NAME}
      caddy.reverse_proxy: "{{upstreams 9091}}"
      caddy.tls.dns: "cloudflare ${CADDY_CLOUDFLARE_API_TOKEN}"