services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    volumes:
      - ${CONFIGS_DIR}/bazarr:/config
      - ${MOVIES_DIR}:/movies # optional
      - ${SHOWS_DIR}:/shows # optional
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    # Run through VPN
    network_mode: service:gluetun
    depends_on:
      - gluetun