configs:
  caddyfile:
    content: | # yaml
      (authelia) {
              forward_auth http://authelia:9091 {
                      copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
                      uri /api/authz/forward-auth
              }
      }

      (cloudflare_tls) {
              tls {
                      dns cloudflare ${CADDY_CLOUDFLARE_API_TOKEN}
              }
      }

      ${AUTHELIA_SUBDOMAIN:-authelia}.${DOMAIN_NAME} {
              reverse_proxy authelia:9091
              import cloudflare_tls
      }

      ${WHOAMI_SUBDOMAIN:-whoami}.${DOMAIN_NAME} {
              import authelia
              reverse_proxy whoami:80
              import cloudflare_tls
      }

      ${JELLYFIN_SUBDOMAIN:-jellyfin}.${DOMAIN_NAME} {
              import authelia
              reverse_proxy jellyfin:8096
              import cloudflare_tls
      }

services:
  caddy:
    build:
      dockerfile_inline: |
        FROM caddy:2-builder AS builder

        RUN xcaddy build \
            --with github.com/caddy-dns/cloudflare \
            --with github.com/fabriziosalmi/caddy-waf

        FROM caddy:2

        COPY --from=builder /usr/bin/caddy /usr/bin/caddy

    container_name: caddy
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: udp
        mode: host # HTTP/3
      - published: 2019
        target: 2019
        protocol: tcp
        mode: host # Caddy admin API
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      DOCKER_HOST: tcp://socket-proxy:2375

    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile

    volumes:
      - ${CONFIGS_DIR}/caddy/data:/data
      - ${CONFIGS_DIR}/caddy/config:/config

    networks:
      - proxy
      - docker
    security_opt:
      - no-new-privileges:true

    
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}

    depends_on:
      - socket-proxy

