services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest 
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      #- LANG=fr_FR
      #- LANG=en_US
    ports:
      - 8191:8191
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik: