services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080 # for qbittorrent
      - 51820:51820
      - 51820:51820/udp
      - 46931:46931
      - 46931:46931/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

      # VPN Configuration
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard

      - WIREGUARD_PRIVATE_KEY=${PROTON_WG_PRIVATE_KEY}

      # --- REGION SETTINGS ---
      # Optional: Filter servers by country (e.g. Netherlands, Switzerland, Iceland)
      - SERVER_COUNTRIES=United States
      - SERVER_CITIES=Philadelphia,New York,Secaucus,Ashburn,Washington

      # --- PORT FORWARDING (Crucial for torrent performance) ---      
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on

    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - proxy
    # volumes:
    # - ${COMMON_PATH}:${COMMON_PATH}
    # - ${COMMON_PATH}/gluetun:/tmp/gluetun
      # Port Forwarding
      # Port Forwarding
