services:
  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    # profiles: ["media", "all"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIGS_DIR}/jackett:/config
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.jackett-rtr.rule: Host(`${JACKETT_SUBDOMAIN:-jackett}.${DOMAIN_NAME}`)
      traefik.http.routers.jackett-rtr.entrypoints: websecure
      traefik.http.routers.jackett-rtr.service: jackett-svc
      traefik.http.services.jackett-svc.loadbalancer.server.port: 9117
