services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    # profiles: ["media", "all"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIGS_DIR}/jellyseerr:/app/config
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr-rtr.rule: Host(`${JELLYSEERR_SUBDOMAIN:-jellyseerr}.${DOMAIN_NAME}`)
      traefik.http.routers.jellyseerr-rtr.entrypoints: websecure
      traefik.http.routers.jellyseerr-rtr.service: jellyseerr-svc
      traefik.http.services.jellyseerr-svc.loadbalancer.server.port: 5055
