services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/jellyfin/jellyfin:latest
    # profiles: ["media", "all"]
    ports:
    - 8096:80
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      # AppData
      - ${CONFIGS_DIR}/jellyfin:/config
      - ${CACHE_DIR}/jellyfin:/cache

      # Media
      - ${DOWNLOADS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
      - ${SHOWS_DIR}:/shows
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - proxy
