services:
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/fallenbagel/jellyseerr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIGS_DIR}/jellyseerr:/app/config
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - proxy
