services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - ${CONFIGS_DIR}/prowlarr:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    # Run through VPN
    network_mode: service:gluetun
    depends_on:
      - gluetun
