services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    # profiles: ["media", "arrs", "all"]
    depends_on:
      - gluetun
    environment:
      - WEBUI_PORT=8080
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${CONFIGS_DIR}/qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    network_mode: service:gluetun

