services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    # profiles: ["media", "arrs", "all"]
    depends_on:
      - gluetun
    environment:
      - WEBUI_PORT=8080
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${CONFIGS_DIR}/qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    network_mode: service:gluetun
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent-rtr.rule: Host(`${QBITTORRENT_SUBDOMAIN:-qbittorrent}.${DOMAIN_NAME}`)
      traefik.http.routers.qbittorrent-rtr.entrypoints: websecure
      traefik.http.routers.qbittorrent-rtr.service: qbittorrent-svc
      traefik.http.services.qbittorrent-svc.loadbalancer.server.port: 8080
