services:
  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`${WHOAMI_SUBDOMAIN:-whoami}.${DOMAIN_NAME}`)
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.services.whoami.loadbalancer.server.port: 80
    networks:
      - traefik