services:
  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    labels:
      caddy: ${WHOAMI_SUBDOMAIN:-whoami}.${DOMAIN_NAME}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy